/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as MSlugRouteImport } from './routes/m.$slug'
import { Route as AuthenticatedPlatformIndexRouteImport } from './routes/_authenticated/platform/index'
import { Route as AuthenticatedPlatformRequestsRouteImport } from './routes/_authenticated/platform/requests'
import { Route as AuthenticatedPlatformTenantsRouteImport } from './routes/_authenticated/platform/tenants'
import { Route as AuthenticatedAppSlugIndexRouteImport } from './routes/_authenticated/app/$slug/index'
import { Route as AuthenticatedAppSlugCirclesRouteImport } from './routes/_authenticated/app/$slug/circles'
import { Route as AuthenticatedAppSlugSettingsRouteImport } from './routes/_authenticated/app/$slug/settings'
import { Route as AuthenticatedAppSlugStudentsRouteImport } from './routes/_authenticated/app/$slug/students'
import { Route as AuthenticatedAppSlugTracksRouteImport } from './routes/_authenticated/app/$slug/tracks'
import { Route as AuthenticatedAppSlugVolunteersRouteImport } from './routes/_authenticated/app/$slug/volunteers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlugRoute = MSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlatformIndexRoute =
  AuthenticatedPlatformIndexRouteImport.update({
    id: '/platform/',
    path: '/platform/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformRequestsRoute =
  AuthenticatedPlatformRequestsRouteImport.update({
    id: '/platform/requests',
    path: '/platform/requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformTenantsRoute =
  AuthenticatedPlatformTenantsRouteImport.update({
    id: '/platform/tenants',
    path: '/platform/tenants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlugIndexRoute =
  AuthenticatedAppSlugIndexRouteImport.update({
    id: '/app/$slug/',
    path: '/app/$slug/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlugCirclesRoute =
  AuthenticatedAppSlugCirclesRouteImport.update({
    id: '/app/$slug/circles',
    path: '/app/$slug/circles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlugSettingsRoute =
  AuthenticatedAppSlugSettingsRouteImport.update({
    id: '/app/$slug/settings',
    path: '/app/$slug/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlugStudentsRoute =
  AuthenticatedAppSlugStudentsRouteImport.update({
    id: '/app/$slug/students',
    path: '/app/$slug/students',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlugTracksRoute =
  AuthenticatedAppSlugTracksRouteImport.update({
    id: '/app/$slug/tracks',
    path: '/app/$slug/tracks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlugVolunteersRoute =
  AuthenticatedAppSlugVolunteersRouteImport.update({
    id: '/app/$slug/volunteers',
    path: '/app/$slug/volunteers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/plans': typeof PlansRoute
  '/roles': typeof RolesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invite/$token': typeof InviteTokenRoute
  '/m/$slug': typeof MSlugRoute
  '/platform/requests': typeof AuthenticatedPlatformRequestsRoute
  '/platform/tenants': typeof AuthenticatedPlatformTenantsRoute
  '/platform/': typeof AuthenticatedPlatformIndexRoute
  '/app/$slug/circles': typeof AuthenticatedAppSlugCirclesRoute
  '/app/$slug/settings': typeof AuthenticatedAppSlugSettingsRoute
  '/app/$slug/students': typeof AuthenticatedAppSlugStudentsRoute
  '/app/$slug/tracks': typeof AuthenticatedAppSlugTracksRoute
  '/app/$slug/volunteers': typeof AuthenticatedAppSlugVolunteersRoute
  '/app/$slug/': typeof AuthenticatedAppSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/plans': typeof PlansRoute
  '/roles': typeof RolesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invite/$token': typeof InviteTokenRoute
  '/m/$slug': typeof MSlugRoute
  '/platform/requests': typeof AuthenticatedPlatformRequestsRoute
  '/platform/tenants': typeof AuthenticatedPlatformTenantsRoute
  '/platform': typeof AuthenticatedPlatformIndexRoute
  '/app/$slug/circles': typeof AuthenticatedAppSlugCirclesRoute
  '/app/$slug/settings': typeof AuthenticatedAppSlugSettingsRoute
  '/app/$slug/students': typeof AuthenticatedAppSlugStudentsRoute
  '/app/$slug/tracks': typeof AuthenticatedAppSlugTracksRoute
  '/app/$slug/volunteers': typeof AuthenticatedAppSlugVolunteersRoute
  '/app/$slug': typeof AuthenticatedAppSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/plans': typeof PlansRoute
  '/roles': typeof RolesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/invite/$token': typeof InviteTokenRoute
  '/m/$slug': typeof MSlugRoute
  '/_authenticated/platform/requests': typeof AuthenticatedPlatformRequestsRoute
  '/_authenticated/platform/tenants': typeof AuthenticatedPlatformTenantsRoute
  '/_authenticated/platform/': typeof AuthenticatedPlatformIndexRoute
  '/_authenticated/app/$slug/circles': typeof AuthenticatedAppSlugCirclesRoute
  '/_authenticated/app/$slug/settings': typeof AuthenticatedAppSlugSettingsRoute
  '/_authenticated/app/$slug/students': typeof AuthenticatedAppSlugStudentsRoute
  '/_authenticated/app/$slug/tracks': typeof AuthenticatedAppSlugTracksRoute
  '/_authenticated/app/$slug/volunteers': typeof AuthenticatedAppSlugVolunteersRoute
  '/_authenticated/app/$slug/': typeof AuthenticatedAppSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/features'
    | '/plans'
    | '/roles'
    | '/dashboard'
    | '/invite/$token'
    | '/m/$slug'
    | '/platform/requests'
    | '/platform/tenants'
    | '/platform/'
    | '/app/$slug/circles'
    | '/app/$slug/settings'
    | '/app/$slug/students'
    | '/app/$slug/tracks'
    | '/app/$slug/volunteers'
    | '/app/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/features'
    | '/plans'
    | '/roles'
    | '/dashboard'
    | '/invite/$token'
    | '/m/$slug'
    | '/platform/requests'
    | '/platform/tenants'
    | '/platform'
    | '/app/$slug/circles'
    | '/app/$slug/settings'
    | '/app/$slug/students'
    | '/app/$slug/tracks'
    | '/app/$slug/volunteers'
    | '/app/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/features'
    | '/plans'
    | '/roles'
    | '/_authenticated/dashboard'
    | '/invite/$token'
    | '/m/$slug'
    | '/_authenticated/platform/requests'
    | '/_authenticated/platform/tenants'
    | '/_authenticated/platform/'
    | '/_authenticated/app/$slug/circles'
    | '/_authenticated/app/$slug/settings'
    | '/_authenticated/app/$slug/students'
    | '/_authenticated/app/$slug/tracks'
    | '/_authenticated/app/$slug/volunteers'
    | '/_authenticated/app/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  PlansRoute: typeof PlansRoute
  RolesRoute: typeof RolesRoute
  InviteTokenRoute: typeof InviteTokenRoute
  MSlugRoute: typeof MSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slug': {
      id: '/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof MSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/platform/': {
      id: '/_authenticated/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof AuthenticatedPlatformIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/requests': {
      id: '/_authenticated/platform/requests'
      path: '/platform/requests'
      fullPath: '/platform/requests'
      preLoaderRoute: typeof AuthenticatedPlatformRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/tenants': {
      id: '/_authenticated/platform/tenants'
      path: '/platform/tenants'
      fullPath: '/platform/tenants'
      preLoaderRoute: typeof AuthenticatedPlatformTenantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/$slug/': {
      id: '/_authenticated/app/$slug/'
      path: '/app/$slug'
      fullPath: '/app/$slug/'
      preLoaderRoute: typeof AuthenticatedAppSlugIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/$slug/circles': {
      id: '/_authenticated/app/$slug/circles'
      path: '/app/$slug/circles'
      fullPath: '/app/$slug/circles'
      preLoaderRoute: typeof AuthenticatedAppSlugCirclesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/$slug/settings': {
      id: '/_authenticated/app/$slug/settings'
      path: '/app/$slug/settings'
      fullPath: '/app/$slug/settings'
      preLoaderRoute: typeof AuthenticatedAppSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/$slug/students': {
      id: '/_authenticated/app/$slug/students'
      path: '/app/$slug/students'
      fullPath: '/app/$slug/students'
      preLoaderRoute: typeof AuthenticatedAppSlugStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/$slug/tracks': {
      id: '/_authenticated/app/$slug/tracks'
      path: '/app/$slug/tracks'
      fullPath: '/app/$slug/tracks'
      preLoaderRoute: typeof AuthenticatedAppSlugTracksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/$slug/volunteers': {
      id: '/_authenticated/app/$slug/volunteers'
      path: '/app/$slug/volunteers'
      fullPath: '/app/$slug/volunteers'
      preLoaderRoute: typeof AuthenticatedAppSlugVolunteersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPlatformRequestsRoute: typeof AuthenticatedPlatformRequestsRoute
  AuthenticatedPlatformTenantsRoute: typeof AuthenticatedPlatformTenantsRoute
  AuthenticatedPlatformIndexRoute: typeof AuthenticatedPlatformIndexRoute
  AuthenticatedAppSlugCirclesRoute: typeof AuthenticatedAppSlugCirclesRoute
  AuthenticatedAppSlugSettingsRoute: typeof AuthenticatedAppSlugSettingsRoute
  AuthenticatedAppSlugStudentsRoute: typeof AuthenticatedAppSlugStudentsRoute
  AuthenticatedAppSlugTracksRoute: typeof AuthenticatedAppSlugTracksRoute
  AuthenticatedAppSlugVolunteersRoute: typeof AuthenticatedAppSlugVolunteersRoute
  AuthenticatedAppSlugIndexRoute: typeof AuthenticatedAppSlugIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPlatformRequestsRoute: AuthenticatedPlatformRequestsRoute,
  AuthenticatedPlatformTenantsRoute: AuthenticatedPlatformTenantsRoute,
  AuthenticatedPlatformIndexRoute: AuthenticatedPlatformIndexRoute,
  AuthenticatedAppSlugCirclesRoute: AuthenticatedAppSlugCirclesRoute,
  AuthenticatedAppSlugSettingsRoute: AuthenticatedAppSlugSettingsRoute,
  AuthenticatedAppSlugStudentsRoute: AuthenticatedAppSlugStudentsRoute,
  AuthenticatedAppSlugTracksRoute: AuthenticatedAppSlugTracksRoute,
  AuthenticatedAppSlugVolunteersRoute: AuthenticatedAppSlugVolunteersRoute,
  AuthenticatedAppSlugIndexRoute: AuthenticatedAppSlugIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  PlansRoute: PlansRoute,
  RolesRoute: RolesRoute,
  InviteTokenRoute: InviteTokenRoute,
  MSlugRoute: MSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
